language: node_js
node_js:
  - "stable"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - "npm install -g typescript"
  - "npm install -g gulp"
  - "npm install -g tsd"
  - "tsd install"
script: npm run test:ci
